-- AlterTable
ALTER TABLE "Source" ADD COLUMN     "mapLat" DOUBLE PRECISION,
ADD COLUMN "mapLng" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PvzPoint" ADD COLUMN     "mapLat" DOUBLE PRECISION,
ADD COLUMN "mapLng" DOUBLE PRECISION;
